/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Authorization: typeof import('./src/components/Authorization.vue')['default']
    Essay: typeof import('./src/components/Essay.vue')['default']
    EssayImage: typeof import('./src/components/EssayImage.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Instructions: typeof import('./src/components/Instructions.vue')['default']
    InstructionsPdf: typeof import('./src/components/InstructionsPdf.vue')['default']
    Items: typeof import('./src/components/Items.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    Marking: typeof import('./src/components/Marking.vue')['default']
    MarkingComment: typeof import('./src/components/MarkingComment.vue')['default']
    MarkingCommentCriteria: typeof import('./src/components/MarkingCommentCriteria.vue')['default']
    MarkingComments: typeof import('./src/components/MarkingComments.vue')['default']
    MarkingGeneralCriteria: typeof import('./src/components/MarkingGeneralCriteria.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OtherSummary: typeof import('./src/components/OtherSummary.vue')['default']
    OwnSummary: typeof import('./src/components/OwnSummary.vue')['default']
    OwnSummaryIncludes: typeof import('./src/components/OwnSummaryIncludes.vue')['default']
    OwnSummaryPoints: typeof import('./src/components/OwnSummaryPoints.vue')['default']
    OwnSummaryText: typeof import('./src/components/OwnSummaryText.vue')['default']
    Resources: typeof import('./src/components/Resources.vue')['default']
    SendingStatus: typeof import('./src/components/SendingStatus.vue')['default']
    Snippets: typeof import('./src/components/Snippets.vue')['default']
    Solution: typeof import('./src/components/Solution.vue')['default']
    SolutionPdf: typeof import('./src/components/SolutionPdf.vue')['default']
    StartupContent: typeof import('./src/components/StartupContent.vue')['default']
    StitchDecision: typeof import('./src/components/StitchDecision.vue')['default']
    SummaryCriteria: typeof import('./src/components/SummaryCriteria.vue')['default']
    SummaryPoints: typeof import('./src/components/SummaryPoints.vue')['default']
    SummaryText: typeof import('./src/components/SummaryText.vue')['default']
    SumOfPoints: typeof import('./src/components/SumOfPoints.vue')['default']
  }
}
